/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robot.glb 
Author: GatoBugadoBR (https://sketchfab.com/GatoBugadoBR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sylvie-fortnite-skin-e8eb0676ed83470581069c4fed771d35
Title: Sylvie - Fortnite Skin
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/robot.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_363.geometry} material={materials.F_MED_EmberRae_Body_5abe865} skeleton={nodes.Object_363.skeleton} />
          <skinnedMesh geometry={nodes.Object_364.geometry} material={materials.F_MED_EmberRae_eyes_745fbd62} skeleton={nodes.Object_364.skeleton} />
          <skinnedMesh geometry={nodes.Object_365.geometry} material={materials.F_MED_EmberRae_Head_5c765ff0} skeleton={nodes.Object_365.skeleton} />
          <skinnedMesh geometry={nodes.Object_366.geometry} material={materials.F_MED_EmberRae_FaceAcc_4b6d9e31} skeleton={nodes.Object_366.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robot.glb')
